// swift-tools-version: 5.9
import PackageDescription

// The amba SDK for Swift — published variant.
//
// This file is generated by `.github/workflows/release-amba-swift.yml`
// when publishing to the SPM mirror at github.com/layers/amba-sdk-ios.
// It references `AmbaCoreFFI.xcframework.zip` as a remote `binaryTarget`
// (URL + SHA-256 checksum) hosted on the matching GitHub Release. SPM
// downloads and verifies the zip during `swift package resolve` — no
// xcframework is committed to the mirror repo (the simulator slice
// exceeds GitHub's 100 MB per-file hard limit).
//
// Placeholders substituted by the workflow:
//   https://github.com/layers/amba-sdk-ios/releases/download/1.0.0/AmbaCoreFFI.xcframework.zip       Release asset download URL (HTTPS, public).
//   42c67819873f10d14b394a7751a7b6fc456317636d224bf4624e669ba5f4eca6  SHA-256 of the zip, as computed by `swift package
//                 compute-checksum` (lowercase hex, no prefix).

let package = Package(
    name: "Amba",
    platforms: [
        .iOS(.v14),
        .macOS(.v12),
        .tvOS(.v14),
        .watchOS(.v7),
    ],
    products: [
        .library(name: "Amba", targets: ["Amba"]),
    ],
    targets: [
        .binaryTarget(
            name: "AmbaCoreFFI",
            url: "https://github.com/layers/amba-sdk-ios/releases/download/1.0.0/AmbaCoreFFI.xcframework.zip",
            checksum: "42c67819873f10d14b394a7751a7b6fc456317636d224bf4624e669ba5f4eca6"
        ),
        .target(
            name: "Amba",
            dependencies: ["AmbaCoreFFI"],
            path: "Sources/Amba",
            resources: [
                .copy("PrivacyInfo.xcprivacy"),
            ]
        ),
        .testTarget(
            name: "AmbaTests",
            dependencies: ["Amba"],
            path: "Tests/AmbaTests"
        ),
        // Customer-shoes smoke. Skipped by default (returns XCTSkip
        // when AMBA_API_URL is unset) so local `swift test` still
        // works without staging credentials. CI invokes it explicitly
        // via `swift test --filter AmbaIntegrationTests`.
        .testTarget(
            name: "AmbaIntegrationTests",
            dependencies: ["Amba"],
            path: "Tests/AmbaIntegrationTests"
        ),
        // Docs-quickstart smoke. Reads pre-minted credentials from env
        // (AMBA_API_KEY + AMBA_API_URL exported by the bash bootstrap
        // in e2e/customer-smoke-docs.sh) and drives the 4-step docs
        // journey: configure → track → anonymous sign-in → collections
        // insert into `posts`. Skipped by default; CI invokes via
        // `swift test --filter AmbaDocsSmokeTests`.
        .testTarget(
            name: "AmbaDocsSmokeTests",
            dependencies: ["Amba"],
            path: "Tests/AmbaDocsSmokeTests"
        ),
    ]
)
