// swift-tools-version: 5.9
import PackageDescription

// The amba SDK for Swift — published variant.
//
// This file is generated by `.github/workflows/release-amba-swift.yml`
// when publishing to the SPM mirror at github.com/layers/amba-sdk-ios.
// It references `AmbaCoreFFI.xcframework.zip` as a remote `binaryTarget`
// (URL + SHA-256 checksum) hosted on the matching GitHub Release. SPM
// downloads and verifies the zip during `swift package resolve` — no
// xcframework is committed to the mirror repo (the simulator slice
// exceeds GitHub's 100 MB per-file hard limit).
//
// The workflow substitutes the asset URL into the `url:` argument and
// the lowercase-hex SHA-256 (from `swift package compute-checksum`)
// into the `checksum:` argument below. Placeholders intentionally only
// appear in those two argument positions so a stray sed-substitution
// can't accidentally rewrite this comment block.

let package = Package(
    name: "Amba",
    platforms: [
        .iOS(.v14),
        .macOS(.v12),
        .tvOS(.v14),
        .watchOS(.v7),
    ],
    products: [
        .library(name: "Amba", targets: ["Amba"]),
    ],
    targets: [
        .binaryTarget(
            name: "AmbaCoreFFI",
            url: "https://github.com/layers/amba-sdk-ios/releases/download/1.0.1/AmbaCoreFFI.xcframework.zip",
            checksum: "4e5e067103a4f7ece7c47dabc99b4a52188fc0afc6bc5c328389b9e8e28c4b86"
        ),
        .target(
            name: "Amba",
            dependencies: ["AmbaCoreFFI"],
            path: "Sources/Amba",
            resources: [
                .copy("PrivacyInfo.xcprivacy"),
            ]
        ),
        .testTarget(
            name: "AmbaTests",
            dependencies: ["Amba"],
            path: "Tests/AmbaTests"
        ),
        // Customer-shoes smoke. Skipped by default (returns XCTSkip
        // when AMBA_API_URL is unset) so local `swift test` still
        // works without staging credentials. CI invokes it explicitly
        // via `swift test --filter AmbaIntegrationTests`.
        .testTarget(
            name: "AmbaIntegrationTests",
            dependencies: ["Amba"],
            path: "Tests/AmbaIntegrationTests"
        ),
        // Docs-quickstart smoke. Reads pre-minted credentials from env
        // (AMBA_API_KEY + AMBA_API_URL exported by the bash bootstrap
        // in e2e/customer-smoke-docs.sh) and drives the 4-step docs
        // journey: configure → track → anonymous sign-in → collections
        // insert into `posts`. Skipped by default; CI invokes via
        // `swift test --filter AmbaDocsSmokeTests`.
        .testTarget(
            name: "AmbaDocsSmokeTests",
            dependencies: ["Amba"],
            path: "Tests/AmbaDocsSmokeTests"
        ),
    ]
)
